home_page/urls.py
from django.urls import path, include, re_path
from . import views
from rest_framework import routers

app_name = "home_page"

router = routers.DefaultRouter()
router.register(r"url", views.UrlViewSet)


urlpatterns = [
    path("", views.index, name="index"),
    path("", include("django.contrib.auth.urls")),
    path("manage_url/<int:UsersUrl_id>/", views.manage_url, name="manage_url"),
    path("<int:UsersUrl_id>/", views.delete_url, name="delete_url"),
    path("<short>/", views.redirect_url, name="redirect_url"),
    path("", include(router.urls)),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
]

url/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("users.urls")),
    path("", include("home_page.urls")),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = "users"

urlpatterns = [
    path("", include("django.contrib.auth.urls")),
    path("register/", views.register, name="register"),
]

home_page/models.py
from django.db import models
from django.contrib.auth.models import User


class UsersUrl(models.Model):
    url = models.CharField(max_length=200)
    short = models.CharField(
        max_length=10, blank=True, unique=True, error_messages={"unique": ""}
    )
    date_added = models.DateTimeField(null=True)
    click_count = models.IntegerField(default=0)
    url_content = models.TextField(max_length=500, blank=True)

    def __str__(self):
        return f"{self.url[:150]}..."

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

home_page/forms.py
from django import forms
from .models import UsersUrl


class UrlForm(forms.ModelForm):
    class Meta:
        model = UsersUrl
        fields = [
            "url",
            "short",
        ]
        labels = {
            "url": "",
            "short": "",
        }
        widgets = {
            "url": forms.TextInput(
                attrs={
                    "size": "50",
                    "placeholder": "Your URL",
                }
            ),
            "short": forms.TextInput(
                attrs={
                    "size": "35",
                    "placeholder": "Your short URL(optional)",
                },
            ),
        }


class ManageForm(forms.ModelForm):
    class Meta:
        model = UsersUrl
        fields = ["short", "url_content", "click_count", "date_added"]
        labels = {"short": "", "url_content": "", "click_count": "", "date_added": ""}
        widgets = {}

home_page/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from .forms import UrlForm, ManageForm
from .models import UsersUrl
from random import randint
import random, string
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from bs4 import BeautifulSoup
import requests
from django.utils import timezone
from rest_framework import viewsets
from .serializers import UrlSerializer


def index(request):
    if request.method == "POST":
        form = UrlForm(request.POST)
        if form.is_valid():
            if form.cleaned_data["short"] == "":
                short = "".join(random.choice(string.ascii_letters) for x in range(10))
                input_url = UsersUrl(url=form.cleaned_data["url"], short=short)
                input_url.date_added = timezone.now()
                input_url.save()
                return redirect("home_page:index")

            else:
                input_url.date_added = timezone.now()
                input_url = form.save()
                return redirect("home_page:index")
    else:
        form = UrlForm()

    urls = UsersUrl.objects.all()
    context = {"form": form, "urls": urls}
    return render(request, "home_page/index.html", context)


def delete_url(request, UsersUrl_id):
    urls = get_object_or_404(UsersUrl, id=UsersUrl_id)
    if request.method == "GET":
        urls.delete()
        return redirect("home_page:index")
    return render(request, "home_page/index.html", context)


def redirect_url(request, short):
    fullurl = get_object_or_404(UsersUrl, short=short)
    fullurl.click_count += 1
    fullurl.save()

    page = requests.get(fullurl.url)
    soup = BeautifulSoup(page.text, "html.parser")

    content = soup.find("title")
    fullurl.url_content += content.text
    fullurl.save()
    return HttpResponseRedirect(fullurl.url)


def manage_url(request, UsersUrl_id):
    if request.method != "POST":
        form = ManageForm(request.POST)
        urls = UsersUrl.objects.get(id=UsersUrl_id)
    context = {"form": form, "urls": urls}
    return render(request, "home_page/manage_url.html", context)


class UrlViewSet(viewsets.ModelViewSet):
    queryset = UsersUrl.objects.all().order_by("id")
    serializer_class = UrlSerializer

users/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


def register(request):
    """This one allows to register new user and redirects to the home page"""
    if request.method != "POST":
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect("home_page:index")
    context = {"form": form}
    return render(request, "registration/register.html", context)

home_page/templates/home_page/base.html
{% load bootstrap4 %}
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
<!doctype html>
<html lang="us">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,
      shrink-to-fit=no">
    <title>Blog</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4 border">
      <a class="navbar-brand" href="{% url 'home_page:index' %}">Python URL Shortner</a>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
      </ul>
      <ul class="navbar-nav ml-auto">
          </li>
           <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin Panel</a>
          </li>
        {% if user.is_authenticated %}
          <li class="nav-item">
            <span class="navbar-text">Signed in as {{ user.username }}.</span>
          </li>
          <li class="nav-item navbar-dark bg-dark">
            <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:register' %}">Sign up</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:login' %}">Login</a></li>
        {% endif %}
      </ul>
    </div>
  </nav>

  <main role="main" class="container">
    <div class="pb-2 mb-2 border-bottom">
         {% block page_header %}{% endblock page_header %}
    </div>
    <div>
      {% block content %}{% endblock content %}
    </div>
  </main>
</body>
</html>

home_page/templates/home_page/index.html
{% extends "./base.html" %}
{% load bootstrap_icons %}

{% block page_header %}
	<form method="POST">
		<div class="form">
   		{% csrf_token %}
      {{ form.url }}
      {{ form.short }}
		<button type="submit" class="btn btn-primary">Create short URL</button>
		</div>
    <div>
    {% if form.errors %}
      <div class="alert alert-danger" role="alert">
        This short URL is already exists.
      </div>
    {% endif %}
	</form>
{% endblock page_header %}

{% block content %}
<table class="table">
  <thead>
	 <tr>
      <th scope="col">URL</th>
      <th scope="col">Text</th>
      <th scope="col">Clicks</th>
      <th scope="col">Short URL</th>
      <th scope="col">Created</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
  	{% for url in urls %}
    <tr>
      <td><a href="{% url 'home_page:manage_url' url.id%}">{{ url }}</td>
      <td>{{ url.url_content }}</td>
      <td>{{ url.click_count }}</td>
      <td><a href="{% url 'home_page:redirect_url' url.short %}">{{ url.short }}</td>
      <td>{{ url.date_added|date:'d M Y H:i'}}</td>
      <td><a href="{% url 'home_page:delete_url' url.id %}"><i class="fas fa-trash-alt"></a></i></td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock content %}

home_page/templates/home_page/manage_url.html
{% extends "./base.html" %}
{% load bootstrap4 %}

{% block page_header %}
	<h4>{{ urls|urlize }}</h4>
{% endblock page_header %}
{% block content %}
<label class="sr-only" for="short">Short Url</label>
  <div class="input-group mb-2 mr-sm-2">
    <div class="input-group-prepend">
      <div class="input-group-text">http://localhost:8000/</div>
    </div>
    <input type="text" name="short" class="form-control" id="short"value="{{ urls.short }}">
  </div>

  <form>
    <div class="form-group">
    <textarea class="form-control" rows="13">{{ urls.url_content }}</textarea>
  </div>
  <div class="row">
    <div class="col">
      <input type="text" class="form-control" value="{{ urls.date_added }}">
    </div>
    <div class="col">
      <input type="text" class="form-control" value="{{ urls.click_count }}">
    </div>
  </div>

</form>

 {% endblock content %}